-- #######################################
-- Generated by Easy AMM Poses
-- #######################################

return {
  modder = "test",
  category = "EAP Test Pack",
  entity_path = "wolv_internal\\controller\\wolv_fem_love_v1.ent",
  
  anims = {        
      ["Man Average"] = {},                    
      ["Woman Average"] = {},                   
      ["Big"] = {},                             
      ["Child"] = {},                           
      ["Fat"] = {},                             
      ["Man Massive"] = {},                        
      ["Player Man"] = {},                      
      ["Player Woman"] = {},                    
  }
}


